// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `from`, `from`, `from`

/// Opens the account's key database, sealed with `store_key` (32 bytes from the platform keystore).
/// `expect_existing`: the keystore already held this key, so the database must exist (fails closed otherwise).
Future<void> init({
  required String dbPath,
  required List<int> storeKey,
  required bool expectExisting,
}) => RustLib.instance.api.crateApiInit(
  dbPath: dbPath,
  storeKey: storeKey,
  expectExisting: expectExisting,
);

Future<Identity> identity() => RustLib.instance.api.crateApiIdentity();

/// JSON of `{identity, rotated, signedPreKey}` (signal.js `prekeys()`).
Future<String> preparePrekeys({required BigInt nowMs}) =>
    RustLib.instance.api.crateApiPreparePrekeys(nowMs: nowMs);

/// JSON array of `{id, key}` one-time prekeys to upload.
Future<String> oneTimePrekeys({required BigInt count}) =>
    RustLib.instance.api.crateApiOneTimePrekeys(count: count);

/// `Some(envelope)`, or `None` when there is no sending session: fetch the bundle and call again with it.
Future<String?> encryptTo({
  required String contactId,
  required String plaintextJson,
  String? bundleJson,
}) => RustLib.instance.api.crateApiEncryptTo(
  contactId: contactId,
  plaintextJson: plaintextJson,
  bundleJson: bundleJson,
);

Future<Decrypted> decryptFrom({
  required String contactId,
  required String envelope,
  Identity? publishedIdentity,
}) => RustLib.instance.api.crateApiDecryptFrom(
  contactId: contactId,
  envelope: envelope,
  publishedIdentity: publishedIdentity,
);

/// After the message is stored. `rotate` when the payload was the peer's `{type:'rotate'}` session reset.
Future<bool> commit({required String pendingId, required bool rotate}) =>
    RustLib.instance.api.crateApiCommit(pendingId: pendingId, rotate: rotate);

Future<void> abort({required String pendingId}) =>
    RustLib.instance.api.crateApiAbort(pendingId: pendingId);

Future<void> notePeer({
  required String contactId,
  required Identity identity,
}) => RustLib.instance.api.crateApiNotePeer(
  contactId: contactId,
  identity: identity,
);

Future<Safety?> safety({
  required String myUsername,
  required String contactId,
  required String theirUsername,
}) => RustLib.instance.api.crateApiSafety(
  myUsername: myUsername,
  contactId: contactId,
  theirUsername: theirUsername,
);

Future<void> setVerified({required String contactId, required bool verified}) =>
    RustLib.instance.api.crateApiSetVerified(
      contactId: contactId,
      verified: verified,
    );

Future<void> acceptChange({required String contactId}) =>
    RustLib.instance.api.crateApiAcceptChange(contactId: contactId);

Future<void> forget({required String contactId}) =>
    RustLib.instance.api.crateApiForget(contactId: contactId);

Future<void> rotate({required String contactId}) =>
    RustLib.instance.api.crateApiRotate(contactId: contactId);

Future<SessionInfo?> sessionInfo({required String contactId}) =>
    RustLib.instance.api.crateApiSessionInfo(contactId: contactId);

Future<void> resetIdentity() => RustLib.instance.api.crateApiResetIdentity();

BigInt rotationInterval({required BigInt mine, required BigInt theirs}) =>
    RustLib.instance.api.crateApiRotationInterval(mine: mine, theirs: theirs);

String sasNewNonce() => RustLib.instance.api.crateApiSasNewNonce();

String sasCommitment({required String nonce}) =>
    RustLib.instance.api.crateApiSasCommitment(nonce: nonce);

bool sasCheckReveal({
  required String peerCommitment,
  required String peerNonce,
}) => RustLib.instance.api.crateApiSasCheckReveal(
  peerCommitment: peerCommitment,
  peerNonce: peerNonce,
);

String sasCode({
  required String localSdp,
  required String remoteSdp,
  required String myNonce,
  required String peerNonce,
}) => RustLib.instance.api.crateApiSasCode(
  localSdp: localSdp,
  remoteSdp: remoteSdp,
  myNonce: myNonce,
  peerNonce: peerNonce,
);

/// A core failure. `code` is the web client's vocabulary (replay, malformed, auth, …); `None` is transient.
class CoreError implements FrbException {
  final String? code;
  final String message;

  const CoreError({this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

class Decrypted {
  final String pendingId;
  final String plaintextJson;
  final bool identityChanged;
  final bool firstContact;
  final Identity? identity;

  const Decrypted({
    required this.pendingId,
    required this.plaintextJson,
    required this.identityChanged,
    required this.firstContact,
    this.identity,
  });

  @override
  int get hashCode =>
      pendingId.hashCode ^
      plaintextJson.hashCode ^
      identityChanged.hashCode ^
      firstContact.hashCode ^
      identity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Decrypted &&
          runtimeType == other.runtimeType &&
          pendingId == other.pendingId &&
          plaintextJson == other.plaintextJson &&
          identityChanged == other.identityChanged &&
          firstContact == other.firstContact &&
          identity == other.identity;
}

class Identity {
  final String dh;
  final String sign;

  const Identity({required this.dh, required this.sign});

  @override
  int get hashCode => dh.hashCode ^ sign.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Identity &&
          runtimeType == other.runtimeType &&
          dh == other.dh &&
          sign == other.sign;
}

class Safety {
  final String number;
  final bool verified;
  final bool changed;
  final bool blocked;

  const Safety({
    required this.number,
    required this.verified,
    required this.changed,
    required this.blocked,
  });

  @override
  int get hashCode =>
      number.hashCode ^ verified.hashCode ^ changed.hashCode ^ blocked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Safety &&
          runtimeType == other.runtimeType &&
          number == other.number &&
          verified == other.verified &&
          changed == other.changed &&
          blocked == other.blocked;
}

class SessionInfo {
  final String sid;
  final BigInt startedAt;

  const SessionInfo({required this.sid, required this.startedAt});

  @override
  int get hashCode => sid.hashCode ^ startedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionInfo &&
          runtimeType == other.runtimeType &&
          sid == other.sid &&
          startedAt == other.startedAt;
}
