// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -537330586;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'chatcore_bridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiAbort({required String pendingId});

  Future<void> crateApiAcceptChange({required String contactId});

  Future<bool> crateApiCommit({
    required String pendingId,
    required bool rotate,
  });

  Future<Decrypted> crateApiDecryptFrom({
    required String contactId,
    required String envelope,
    Identity? publishedIdentity,
  });

  Future<String?> crateApiEncryptTo({
    required String contactId,
    required String plaintextJson,
    String? bundleJson,
  });

  Future<void> crateApiForget({required String contactId});

  Future<Identity> crateApiIdentity();

  Future<void> crateApiInit({
    required String dbPath,
    required List<int> storeKey,
    required bool expectExisting,
  });

  Future<void> crateApiNotePeer({
    required String contactId,
    required Identity identity,
  });

  Future<String> crateApiOneTimePrekeys({required BigInt count});

  Future<String> crateApiPreparePrekeys({required BigInt nowMs});

  Future<void> crateApiResetIdentity();

  Future<void> crateApiRotate({required String contactId});

  BigInt crateApiRotationInterval({
    required BigInt mine,
    required BigInt theirs,
  });

  Future<Safety?> crateApiSafety({
    required String myUsername,
    required String contactId,
    required String theirUsername,
  });

  bool crateApiSasCheckReveal({
    required String peerCommitment,
    required String peerNonce,
  });

  String crateApiSasCode({
    required String localSdp,
    required String remoteSdp,
    required String myNonce,
    required String peerNonce,
  });

  String crateApiSasCommitment({required String nonce});

  String crateApiSasNewNonce();

  Future<SessionInfo?> crateApiSessionInfo({required String contactId});

  Future<void> crateApiSetVerified({
    required String contactId,
    required bool verified,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiAbort({required String pendingId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pendingId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiAbortConstMeta,
        argValues: [pendingId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAbortConstMeta =>
      const TaskConstMeta(debugName: "abort", argNames: ["pendingId"]);

  @override
  Future<void> crateApiAcceptChange({required String contactId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiAcceptChangeConstMeta,
        argValues: [contactId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAcceptChangeConstMeta =>
      const TaskConstMeta(debugName: "accept_change", argNames: ["contactId"]);

  @override
  Future<bool> crateApiCommit({
    required String pendingId,
    required bool rotate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pendingId, serializer);
          sse_encode_bool(rotate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiCommitConstMeta,
        argValues: [pendingId, rotate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommitConstMeta => const TaskConstMeta(
    debugName: "commit",
    argNames: ["pendingId", "rotate"],
  );

  @override
  Future<Decrypted> crateApiDecryptFrom({
    required String contactId,
    required String envelope,
    Identity? publishedIdentity,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          sse_encode_String(envelope, serializer);
          sse_encode_opt_box_autoadd_identity(publishedIdentity, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_decrypted,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiDecryptFromConstMeta,
        argValues: [contactId, envelope, publishedIdentity],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDecryptFromConstMeta => const TaskConstMeta(
    debugName: "decrypt_from",
    argNames: ["contactId", "envelope", "publishedIdentity"],
  );

  @override
  Future<String?> crateApiEncryptTo({
    required String contactId,
    required String plaintextJson,
    String? bundleJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          sse_encode_String(plaintextJson, serializer);
          sse_encode_opt_String(bundleJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiEncryptToConstMeta,
        argValues: [contactId, plaintextJson, bundleJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEncryptToConstMeta => const TaskConstMeta(
    debugName: "encrypt_to",
    argNames: ["contactId", "plaintextJson", "bundleJson"],
  );

  @override
  Future<void> crateApiForget({required String contactId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiForgetConstMeta,
        argValues: [contactId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiForgetConstMeta =>
      const TaskConstMeta(debugName: "forget", argNames: ["contactId"]);

  @override
  Future<Identity> crateApiIdentity() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIdentityConstMeta =>
      const TaskConstMeta(debugName: "identity", argNames: []);

  @override
  Future<void> crateApiInit({
    required String dbPath,
    required List<int> storeKey,
    required bool expectExisting,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_list_prim_u_8_loose(storeKey, serializer);
          sse_encode_bool(expectExisting, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiInitConstMeta,
        argValues: [dbPath, storeKey, expectExisting],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitConstMeta => const TaskConstMeta(
    debugName: "init",
    argNames: ["dbPath", "storeKey", "expectExisting"],
  );

  @override
  Future<void> crateApiNotePeer({
    required String contactId,
    required Identity identity,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          sse_encode_box_autoadd_identity(identity, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiNotePeerConstMeta,
        argValues: [contactId, identity],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNotePeerConstMeta => const TaskConstMeta(
    debugName: "note_peer",
    argNames: ["contactId", "identity"],
  );

  @override
  Future<String> crateApiOneTimePrekeys({required BigInt count}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(count, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiOneTimePrekeysConstMeta,
        argValues: [count],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOneTimePrekeysConstMeta =>
      const TaskConstMeta(debugName: "one_time_prekeys", argNames: ["count"]);

  @override
  Future<String> crateApiPreparePrekeys({required BigInt nowMs}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(nowMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiPreparePrekeysConstMeta,
        argValues: [nowMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPreparePrekeysConstMeta =>
      const TaskConstMeta(debugName: "prepare_prekeys", argNames: ["nowMs"]);

  @override
  Future<void> crateApiResetIdentity() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiResetIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiResetIdentityConstMeta =>
      const TaskConstMeta(debugName: "reset_identity", argNames: []);

  @override
  Future<void> crateApiRotate({required String contactId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiRotateConstMeta,
        argValues: [contactId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRotateConstMeta =>
      const TaskConstMeta(debugName: "rotate", argNames: ["contactId"]);

  @override
  BigInt crateApiRotationInterval({
    required BigInt mine,
    required BigInt theirs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(mine, serializer);
          sse_encode_u_64(theirs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiRotationIntervalConstMeta,
        argValues: [mine, theirs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRotationIntervalConstMeta => const TaskConstMeta(
    debugName: "rotation_interval",
    argNames: ["mine", "theirs"],
  );

  @override
  Future<Safety?> crateApiSafety({
    required String myUsername,
    required String contactId,
    required String theirUsername,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(myUsername, serializer);
          sse_encode_String(contactId, serializer);
          sse_encode_String(theirUsername, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_safety,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiSafetyConstMeta,
        argValues: [myUsername, contactId, theirUsername],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSafetyConstMeta => const TaskConstMeta(
    debugName: "safety",
    argNames: ["myUsername", "contactId", "theirUsername"],
  );

  @override
  bool crateApiSasCheckReveal({
    required String peerCommitment,
    required String peerNonce,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerCommitment, serializer);
          sse_encode_String(peerNonce, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSasCheckRevealConstMeta,
        argValues: [peerCommitment, peerNonce],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSasCheckRevealConstMeta => const TaskConstMeta(
    debugName: "sas_check_reveal",
    argNames: ["peerCommitment", "peerNonce"],
  );

  @override
  String crateApiSasCode({
    required String localSdp,
    required String remoteSdp,
    required String myNonce,
    required String peerNonce,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(localSdp, serializer);
          sse_encode_String(remoteSdp, serializer);
          sse_encode_String(myNonce, serializer);
          sse_encode_String(peerNonce, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiSasCodeConstMeta,
        argValues: [localSdp, remoteSdp, myNonce, peerNonce],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSasCodeConstMeta => const TaskConstMeta(
    debugName: "sas_code",
    argNames: ["localSdp", "remoteSdp", "myNonce", "peerNonce"],
  );

  @override
  String crateApiSasCommitment({required String nonce}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nonce, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiSasCommitmentConstMeta,
        argValues: [nonce],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSasCommitmentConstMeta =>
      const TaskConstMeta(debugName: "sas_commitment", argNames: ["nonce"]);

  @override
  String crateApiSasNewNonce() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSasNewNonceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSasNewNonceConstMeta =>
      const TaskConstMeta(debugName: "sas_new_nonce", argNames: []);

  @override
  Future<SessionInfo?> crateApiSessionInfo({required String contactId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_session_info,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiSessionInfoConstMeta,
        argValues: [contactId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSessionInfoConstMeta =>
      const TaskConstMeta(debugName: "session_info", argNames: ["contactId"]);

  @override
  Future<void> crateApiSetVerified({
    required String contactId,
    required bool verified,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contactId, serializer);
          sse_encode_bool(verified, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_core_error,
        ),
        constMeta: kCrateApiSetVerifiedConstMeta,
        argValues: [contactId, verified],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetVerifiedConstMeta => const TaskConstMeta(
    debugName: "set_verified",
    argNames: ["contactId", "verified"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Identity dco_decode_box_autoadd_identity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_identity(raw);
  }

  @protected
  Safety dco_decode_box_autoadd_safety(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_safety(raw);
  }

  @protected
  SessionInfo dco_decode_box_autoadd_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_session_info(raw);
  }

  @protected
  CoreError dco_decode_core_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CoreError(
      code: dco_decode_opt_String(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  Decrypted dco_decode_decrypted(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Decrypted(
      pendingId: dco_decode_String(arr[0]),
      plaintextJson: dco_decode_String(arr[1]),
      identityChanged: dco_decode_bool(arr[2]),
      firstContact: dco_decode_bool(arr[3]),
      identity: dco_decode_opt_box_autoadd_identity(arr[4]),
    );
  }

  @protected
  Identity dco_decode_identity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Identity(
      dh: dco_decode_String(arr[0]),
      sign: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Identity? dco_decode_opt_box_autoadd_identity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_identity(raw);
  }

  @protected
  Safety? dco_decode_opt_box_autoadd_safety(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_safety(raw);
  }

  @protected
  SessionInfo? dco_decode_opt_box_autoadd_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_session_info(raw);
  }

  @protected
  Safety dco_decode_safety(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Safety(
      number: dco_decode_String(arr[0]),
      verified: dco_decode_bool(arr[1]),
      changed: dco_decode_bool(arr[2]),
      blocked: dco_decode_bool(arr[3]),
    );
  }

  @protected
  SessionInfo dco_decode_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SessionInfo(
      sid: dco_decode_String(arr[0]),
      startedAt: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Identity sse_decode_box_autoadd_identity(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_identity(deserializer));
  }

  @protected
  Safety sse_decode_box_autoadd_safety(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_safety(deserializer));
  }

  @protected
  SessionInfo sse_decode_box_autoadd_session_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_session_info(deserializer));
  }

  @protected
  CoreError sse_decode_core_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return CoreError(code: var_code, message: var_message);
  }

  @protected
  Decrypted sse_decode_decrypted(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pendingId = sse_decode_String(deserializer);
    var var_plaintextJson = sse_decode_String(deserializer);
    var var_identityChanged = sse_decode_bool(deserializer);
    var var_firstContact = sse_decode_bool(deserializer);
    var var_identity = sse_decode_opt_box_autoadd_identity(deserializer);
    return Decrypted(
      pendingId: var_pendingId,
      plaintextJson: var_plaintextJson,
      identityChanged: var_identityChanged,
      firstContact: var_firstContact,
      identity: var_identity,
    );
  }

  @protected
  Identity sse_decode_identity(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dh = sse_decode_String(deserializer);
    var var_sign = sse_decode_String(deserializer);
    return Identity(dh: var_dh, sign: var_sign);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Identity? sse_decode_opt_box_autoadd_identity(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_identity(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Safety? sse_decode_opt_box_autoadd_safety(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_safety(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SessionInfo? sse_decode_opt_box_autoadd_session_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_session_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Safety sse_decode_safety(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_number = sse_decode_String(deserializer);
    var var_verified = sse_decode_bool(deserializer);
    var var_changed = sse_decode_bool(deserializer);
    var var_blocked = sse_decode_bool(deserializer);
    return Safety(
      number: var_number,
      verified: var_verified,
      changed: var_changed,
      blocked: var_blocked,
    );
  }

  @protected
  SessionInfo sse_decode_session_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sid = sse_decode_String(deserializer);
    var var_startedAt = sse_decode_u_64(deserializer);
    return SessionInfo(sid: var_sid, startedAt: var_startedAt);
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_identity(
    Identity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_identity(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_safety(Safety self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_safety(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_session_info(
    SessionInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_session_info(self, serializer);
  }

  @protected
  void sse_encode_core_error(CoreError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_decrypted(Decrypted self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.pendingId, serializer);
    sse_encode_String(self.plaintextJson, serializer);
    sse_encode_bool(self.identityChanged, serializer);
    sse_encode_bool(self.firstContact, serializer);
    sse_encode_opt_box_autoadd_identity(self.identity, serializer);
  }

  @protected
  void sse_encode_identity(Identity self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.dh, serializer);
    sse_encode_String(self.sign, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_identity(
    Identity? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_identity(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_safety(
    Safety? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_safety(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_session_info(
    SessionInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_session_info(self, serializer);
    }
  }

  @protected
  void sse_encode_safety(Safety self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.number, serializer);
    sse_encode_bool(self.verified, serializer);
    sse_encode_bool(self.changed, serializer);
    sse_encode_bool(self.blocked, serializer);
  }

  @protected
  void sse_encode_session_info(SessionInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sid, serializer);
    sse_encode_u_64(self.startedAt, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
