// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Identity dco_decode_box_autoadd_identity(dynamic raw);

  @protected
  Safety dco_decode_box_autoadd_safety(dynamic raw);

  @protected
  SessionInfo dco_decode_box_autoadd_session_info(dynamic raw);

  @protected
  CoreError dco_decode_core_error(dynamic raw);

  @protected
  Decrypted dco_decode_decrypted(dynamic raw);

  @protected
  Identity dco_decode_identity(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Identity? dco_decode_opt_box_autoadd_identity(dynamic raw);

  @protected
  Safety? dco_decode_opt_box_autoadd_safety(dynamic raw);

  @protected
  SessionInfo? dco_decode_opt_box_autoadd_session_info(dynamic raw);

  @protected
  Safety dco_decode_safety(dynamic raw);

  @protected
  SessionInfo dco_decode_session_info(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Identity sse_decode_box_autoadd_identity(SseDeserializer deserializer);

  @protected
  Safety sse_decode_box_autoadd_safety(SseDeserializer deserializer);

  @protected
  SessionInfo sse_decode_box_autoadd_session_info(SseDeserializer deserializer);

  @protected
  CoreError sse_decode_core_error(SseDeserializer deserializer);

  @protected
  Decrypted sse_decode_decrypted(SseDeserializer deserializer);

  @protected
  Identity sse_decode_identity(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Identity? sse_decode_opt_box_autoadd_identity(SseDeserializer deserializer);

  @protected
  Safety? sse_decode_opt_box_autoadd_safety(SseDeserializer deserializer);

  @protected
  SessionInfo? sse_decode_opt_box_autoadd_session_info(
    SseDeserializer deserializer,
  );

  @protected
  Safety sse_decode_safety(SseDeserializer deserializer);

  @protected
  SessionInfo sse_decode_session_info(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_identity(Identity self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_safety(Safety self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_session_info(
    SessionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_core_error(CoreError self, SseSerializer serializer);

  @protected
  void sse_encode_decrypted(Decrypted self, SseSerializer serializer);

  @protected
  void sse_encode_identity(Identity self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_identity(
    Identity? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_safety(
    Safety? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_session_info(
    SessionInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_safety(Safety self, SseSerializer serializer);

  @protected
  void sse_encode_session_info(SessionInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
