# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1 AS base
WORKDIR /usr/src/app

# run the app
USER bun
EXPOSE 3479/udp
EXPOSE 3478/udp
ENTRYPOINT [ "bun", "main.js" ]