import { randomBytes } from 'node:crypto';
import { mkdir, open, unlink } from 'node:fs/promises';
import { isIP } from 'node:net';
import { resolve } from 'node:path';

// Accept explicit arguments so setup never reads or rewrites the repository's legacy .env.
export function configuration(args: string[]) {
    const [domain, turnHost, publicIP, email, localIP = publicIP] = args;
    const hostname = /^(?=.{1,253}$)(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,63}$/;
    if ((args.length !== 4 && args.length !== 5) || !hostname.test(domain!) || !hostname.test(turnHost!) || isIP(publicIP!) !== 4 || isIP(localIP!) !== 4 || !/^[A-Za-z0-9._+%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/.test(email!)) {
        throw new Error('Usage: bun --no-env-file scripts/setup.ts calls.example.com turn.example.com PUBLIC_IPV4 admin@example.com [LOCAL_IPV4]');
    }
    const secret = () => randomBytes(32).toString('hex');
    const adminToken = secret();
    const turnSecret = secret();
    return {
        env: `DOMAIN=${domain}\nTURN_HOST=${turnHost}\nPUBLIC_IP=${publicIP}\nACME_EMAIL=${email}\nDEPLOY_UID=${process.getuid?.() ?? 1000}\nDEPLOY_GID=${process.getgid?.() ?? 1000}\nADMIN_TOKEN=${adminToken}\nTURN_SECRET=${turnSecret}\n`,
        turn: `# Generated by scripts/setup.ts; this file contains a secret.\nlistening-port=3478\nlistening-ip=0.0.0.0\nrelay-ip=${localIP}\nexternal-ip=${publicIP === localIP ? publicIP : `${publicIP}/${localIP}`}\nmin-port=49160\nmax-port=49259\nrealm=${turnHost}\nserver-name=${turnHost}\nfingerprint\nuse-auth-secret\nstatic-auth-secret=${turnSecret}\nstale-nonce=600\nno-tls\nno-dtls\nno-cli\nno-multicast-peers\nno-tcp-relay\nuser-quota=12\ntotal-quota=120\nmax-bps=2000000\nbps-capacity=100000000\nlog-file=stdout\nsimple-log\nno-software-attribute\n# Block private, loopback, link-local, multicast and reserved relay destinations.\ndenied-peer-ip=0.0.0.0-0.255.255.255\ndenied-peer-ip=10.0.0.0-10.255.255.255\ndenied-peer-ip=100.64.0.0-100.127.255.255\ndenied-peer-ip=127.0.0.0-127.255.255.255\ndenied-peer-ip=169.254.0.0-169.254.255.255\ndenied-peer-ip=172.16.0.0-172.31.255.255\ndenied-peer-ip=192.168.0.0-192.168.255.255\ndenied-peer-ip=224.0.0.0-255.255.255.255\ndenied-peer-ip=::\ndenied-peer-ip=::1\ndenied-peer-ip=fc00::-fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff\ndenied-peer-ip=fe80::-febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff\ndenied-peer-ip=ff00::-ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff\n`,
    };
}

export async function setup(args: string[], directory = resolve(import.meta.dir, '../deploy')) {
    const config = configuration(args);
    await mkdir(directory, { recursive: true, mode: 0o700 });
    const envPath = resolve(directory, '.env');
    const turnPath = resolve(directory, 'turnserver.conf');
    const env = await open(envPath, 'wx', 0o600);
    let turn;
    try { turn = await open(turnPath, 'wx', 0o600); }
    catch (error) { await env.close(); await unlink(envPath); throw error; }
    try {
        await env.writeFile(config.env);
        await turn.writeFile(config.turn);
    } finally { await env.close(); await turn.close(); }
}

if (import.meta.main) {
    try {
        await setup(process.argv.slice(2));
        console.log('Created deploy/.env and deploy/turnserver.conf. Secrets were not printed.');
        console.log('Start on a Linux server: docker compose --env-file deploy/.env up -d --build');
    } catch (error: any) {
        console.error(error.code === 'EEXIST' ? 'Setup refused to overwrite existing deployment configuration.' : error.message);
        process.exitCode = 1;
    }
}
