import { describe, expect, test } from 'bun:test';
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';
import { brotliCompressSync, constants } from 'node:zlib';

// The committed WebAssembly core (scripts/build-wasm.ts): the manifest must describe exactly the files on disk,
// and the module must stay within the size budget from docs/workspace-architecture.md (§4.3).
const dir = new URL('../../packages/signaling/public/core/', import.meta.url);
const manifest = JSON.parse(readFileSync(new URL('manifest.json', dir), 'utf8')) as {
    js: string; wasm: string; sha256: Record<string, string>; bytes: Record<string, number>; wasmBindgen: string;
};

describe('committed WebAssembly core', () => {
    test('the manifest names the only core files on disk and their hashes match', () => {
        const files = readdirSync(dir).filter(name => name !== 'manifest.json').sort();
        expect(files).toEqual([manifest.js, manifest.wasm].sort());
        for (const name of files) {
            const bytes = readFileSync(new URL(name, dir));
            const digest = createHash('sha256').update(bytes).digest('hex');
            expect(manifest.sha256[name]).toBe(digest);
            expect(name).toContain(digest.slice(0, 16));
            expect(manifest.bytes[name]).toBe(bytes.length);
        }
    });
    test('the glue was generated by the wasm-bindgen version the crate pins', () => {
        const pinned = /wasm-bindgen = "=([\d.]+)"/.exec(readFileSync(new URL('../../crates/chatcore-wasm/Cargo.toml', import.meta.url), 'utf8'))![1];
        expect(manifest.wasmBindgen).toBe(pinned);
    });
    test('size budget: at most 2 MB raw and 700 KB brotli', () => {
        const wasm = readFileSync(new URL(manifest.wasm, dir));
        const brotli = brotliCompressSync(wasm, { params: { [constants.BROTLI_PARAM_QUALITY]: 11 } }).length;
        expect(wasm.length).toBeLessThanOrEqual(2 * 1024 * 1024);
        expect(brotli).toBeLessThanOrEqual(700 * 1024);
    });
});
