import { describe, expect, test } from 'bun:test';
import { cpSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { brotliCompressSync, constants } from 'node:zlib';
import { verifyCore } from '../../packages/signaling/core-manifest';
import { startSignaling } from '../../packages/signaling/server';

// The committed WebAssembly core (scripts/build-wasm.ts). verifyCore is what the server runs at startup and
// what build:wasm --check runs before comparing with a rebuild: exact file set, recorded SHA-256 per file.
const dir = fileURLToPath(new URL('../../packages/signaling/public/core/', import.meta.url));
const manifest = JSON.parse(readFileSync(join(dir, 'manifest.json'), 'utf8')) as { js: string; wasm: string; sha256: Record<string, string>; bytes: Record<string, number>; wasmBindgen: string };
const sha = (bytes: Buffer) => createHash('sha256').update(bytes).digest('hex');
/** A scratch copy of the committed core to tamper with. */
function copy() { const target = mkdtempSync(join(tmpdir(), 'core-verify-')); cpSync(dir, target, { recursive: true }); return target; }

describe('committed WebAssembly core', () => {
    test('passes verification: exactly the manifest and its two files, hashes matching', () => {
        expect([...verifyCore(dir).keys()].sort()).toEqual(['manifest.json', manifest.js, manifest.wasm].sort());
        expect(readdirSync(dir).sort()).toEqual(['manifest.json', manifest.js, manifest.wasm].sort());
    });
    test('an extra file in the directory fails verification', () => {
        const target = copy();
        try { writeFileSync(join(target, 'evil.js'), 'alert(1)'); expect(() => verifyCore(target)).toThrow('must contain exactly'); }
        finally { rmSync(target, { recursive: true, force: true }); }
    });
    test('a modified file fails verification', () => {
        const target = copy();
        try {
            const bytes = readFileSync(join(target, manifest.wasm)); bytes[bytes.length - 1] ^= 1;
            writeFileSync(join(target, manifest.wasm), bytes);
            expect(() => verifyCore(target)).toThrow('does not match its recorded SHA-256');
        } finally { rmSync(target, { recursive: true, force: true }); }
    });
    test('a missing file fails verification', () => {
        const target = copy();
        try { rmSync(join(target, manifest.js)); expect(() => verifyCore(target)).toThrow('must contain exactly'); }
        finally { rmSync(target, { recursive: true, force: true }); }
    });
    test('a manifest edited to describe a modified file is self-consistent, so only the rebuild comparison can catch it', () => {
        // Tamper with the wasm, rename it to its new hash and rewrite the manifest: verifyCore can't tell (that's
        // why CI's build:wasm --check rebuilds from source and compares bytes; see tests/interop/core-tamper.mjs).
        const target = copy();
        try {
            const bytes = readFileSync(join(target, manifest.wasm)); bytes[bytes.length - 1] ^= 1;
            const name = `chatcore_bg.${sha(bytes).slice(0, 16)}.wasm`;
            rmSync(join(target, manifest.wasm)); writeFileSync(join(target, name), bytes);
            const edited = { ...manifest, wasm: name, sha256: { [manifest.js]: manifest.sha256[manifest.js], [name]: sha(bytes) } };
            writeFileSync(join(target, 'manifest.json'), JSON.stringify(edited));
            expect(verifyCore(target).has(name)).toBe(true);
        } finally { rmSync(target, { recursive: true, force: true }); }
    });
    test('the server refuses to start with an unverifiable core', () => {
        const target = copy();
        try {
            writeFileSync(join(target, 'extra.wasm'), 'x');
            expect(() => startSignaling({ adminToken: 'wasm-core-test-admin-token-00000000000', origin: 'http://localhost:3000', port: 0, coreDir: target })).toThrow('failed verification');
        } finally { rmSync(target, { recursive: true, force: true }); }
    });
    test('the glue was generated by the wasm-bindgen version the crate pins', () => {
        const pinned = /wasm-bindgen = "=([\d.]+)"/.exec(readFileSync(new URL('../../crates/chatcore-wasm/Cargo.toml', import.meta.url), 'utf8'))![1];
        expect(manifest.wasmBindgen).toBe(pinned);
    });
    test('size budget: at most 2 MB raw and 700 KB brotli', () => {
        const wasm = readFileSync(join(dir, manifest.wasm));
        const brotli = brotliCompressSync(wasm, { params: { [constants.BROTLI_PARAM_QUALITY]: 11 } }).length;
        expect(wasm.length).toBeLessThanOrEqual(2 * 1024 * 1024);
        expect(brotli).toBeLessThanOrEqual(700 * 1024);
    });
});
